version: '3'

services:
    front:
        build:
            context: ./front
            dockerfile: Dockerfile
        ports:
            - "8888:8080"
        depends_on:
        - back

    back:
        build: back
        environment:
            MQTT_HOST: mqtt.sik.party