version: '3'

services:
    front:
        build:
            context: ./front
            dockerfile: Dockerfile
            args:
                apiurl: http://localhost:8889
        ports:
            - "8888:80"
    back:
        build: back
        environment:
            MQTT_HOST: mqtt.sik.party
        ports:
            - "8889:8080"

